[package]
name = "f"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0"
serde_json = "1.0"
notify = { version = "5.0", default-features = false }
tokio = { version = "1", features = ["full"] }
async-trait = "0.1.58"
futures = "0.3.25"
anyhow = "1.0"
atty = "0.2"
